// This file is part of rust-mailjet <https://github.com/nevermille/rust-mailjet>
// Copyright (C) 2023 Camille Nevermind
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, write to the Free Software Foundation,
// Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

/// The contact list identifier, can be an id or an address
pub enum ContactsListIdentifier {
    /// Unique numeric ID assigned to this contact list,
    ListId(i128),
    /// Unique email address generated by Mailjet for this list
    ListAddress(String),
}

impl ToString for ContactsListIdentifier {
    fn to_string(&self) -> String {
        match self {
            ContactsListIdentifier::ListId(v) => v.to_string(),
            ContactsListIdentifier::ListAddress(v) => v.to_string(),
        }
    }
}
