# This is a basic workflow to help you get started with Actions

name: Test code on stable environment

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  clippy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Lint code
        uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
