# This is a basic workflow to help you get started with Actions

name: Test code on stable environment

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: default

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download code
        uses: actions/checkout@v3

      - name: Lint code
        uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy

      - name: Test doc generation
        uses: actions-rs/cargo@v1.0.1
        with:
          command: doc

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: default
    env:
      MJ_KEY: ${{ secrets.MJ_KEY }}
      MJ_SECRET: ${{ secrets.MJ_SECRET }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download code
        uses: actions/checkout@v3

      - name: Execute tests
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
